name: Build PS4 Payload SDK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ps4sdk .

      - name: List build output
        run: docker run --rm --entrypoint "" ps4sdk ls -l /lib/ps4sdk/libPS4
